### ISSUE TITLE
Errors running Codegen

### ISSUE THREAD

**Issue by HiteshDhamecha** [MemberJunction/MJ#201] opened 2024-05-15 14:38 UTC
Hello Team & @hiltongr

I am encountering an issues while running CodeGen. 

Steps: - 
- Create a table with columns containing data types of uniqueidentifier or timestamp
- Run codegen
- Check Command Prompt for errors

**Comment by cadam11** [comment] 2024-05-15 16:27
Duplicate of #202

**Comment by cadam11** [comment] 2024-05-22 03:05
Fixed in #204

**Closed by cadam11** 2024-05-22 03:05 UTC
